# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manager', '0003_auto_20190827_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmanager',
            old_name='due_date',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='tasksmanager',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
