# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manager', '0004_auto_20190827_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmanager',
            name='event_id',
            field=models.IntegerField(default=None),
        ),
    ]
