# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manager', '0005_tasksmanager_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmanager',
            name='event_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
