# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manager', '0006_auto_20190828_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmanager',
            name='event_id',
            field=models.CharField(max_length=200),
        ),
    ]
